after-login-command = []

after-startup-command = [
    'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar',
    # 'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color="glow(0xd943ff64)" inactive_color=0x20494d64 width=8.0'
    'exec-and-forget borders active_color="glow(0xff40e0d0)" inactive_color=0xff708090 width=3.0 hidpi=on ax_focus=true',
    'exec-and-forget brew services restart sketchybar'
]

exec-on-workspace-change = [
    '/bin/bash',
    '-c',
    '/opt/homebrew/opt/sketchybar/bin/sketchybar --trigger aerospace_workspace_change AEROSPACE_FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE AEROSPACE_PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE',
]

#暂时无法创建粘性窗口
#'WIN=$(aerospace list-windows --all | grep "画中画" | cut -d" " -f1); [ -n "$WIN" ] && aerospace move-node-to-workspace --window-id="$WIN" "$AEROSPACE_FOCUSED_WORKSPACE"',

start-at-login = true

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 20

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
#on-focus-changed = ['move-mouse window-lazy-center']

# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
#[workspace-to-monitor-force-assignment]
#1 = 'main'
#2 = 'main'
#3 = 'V32UE'
#4 = 'V32UE'
#5 = 'V32UE'
#6 = '^27W'
#7 = '^27W'
#10 = '^EPSON'

[gaps]
inner.horizontal = [{ monitor."built-in" = 9 }, 9]
inner.vertical = [{ monitor."built-in" = 9 }, 9]
outer.top = [{ monitor."built-in" = 22 }, 54]
outer.bottom = [{ monitor."built-in" = 7 }, 9]
outer.left = [{ monitor."built-in" = 7 }, 9]
outer.right = [{ monitor."built-in" = 7 }, 6]

[exec]
inherit-env-vars = true

[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

#alt-enter = ['exec-and-forget open -n /System/Volumes/Data/Applications/iTerm.app', 'exec-and-forget aerospace resize width -650']

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left --boundaries all-monitors-outer-frame'
alt-j = 'focus down --boundaries all-monitors-outer-frame'
alt-k = 'focus up --boundaries all-monitors-outer-frame'
alt-l = 'focus right --boundaries all-monitors-outer-frame'

ctrl-shift-h = ['join-with left']
ctrl-shift-j = ['join-with down']
ctrl-shift-k = ['join-with up']
ctrl-shift-l = ['join-with right']

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -100'
alt-shift-equal = 'resize smart +100'

alt-1 = 'workspace Brow'
alt-2 = 'workspace Chat'
alt-3 = 'workspace Dev'
alt-4 = 'workspace Read'
alt-5 = 'workspace Wri'
alt-6 = 'workspace Zen'
alt-7 = 'workspace Vork'

alt-b = 'workspace Brow'
alt-c = 'workspace Chat'
alt-d = 'workspace Dev'
alt-r = 'workspace Read'
alt-w = 'workspace Wri'
alt-z = 'workspace Zen'
alt-v = 'workspace Vork'

alt-shift-b = 'move-node-to-workspace Brow'
alt-shift-c = 'move-node-to-workspace Chat'
alt-shift-d = 'move-node-to-workspace Dev'
alt-shift-r = 'move-node-to-workspace Read'
alt-shift-w = 'move-node-to-workspace Wri'
alt-shift-z = 'move-node-to-workspace Zen'
alt-shift-v = 'move-node-to-workspace Vork'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

### skhd use too many ram, thus I rather use aerospace to map hotkeys
# reload aerospace config
cmd-shift-r = [
	'exec-and-forget /opt/homebrew/bin/sketchybar --reload',
	'exec-and-forget brew services restart sketchybar',
	'exec-and-forget brew services restart borders'
]
# system control
cmd-shift-s = ['''exec-and-forget osascript -e 'tell application "System Events" to sleep'''']

cmd-enter = 'exec-and-forget /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~'

#cmd + shift - return : /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~ joshuto

cmd-shift-l = 'exec-and-forget aerospace layout floating tiling; sketchybar --trigger windows_focus'
cmd-shift-f = 'exec-and-forget aerospace fullscreen; sketchybar --trigger windows_focus'
cmd-shift-m = 'exec-and-forget aerospace macos-native-minimize'
cmd-shift-b = 'exec-and-forget aerospace balance-sizes'
cmd-shift-e = '''exec-and-forget open -a 'Sublime Text' /Users/acid/.aerospace.toml /Users/acid/.config/sketchybar/sketchybarrc'''

# open qutebrowser
cmd-shift-o = '''exec-and-forget open -a 'qutebrowser''''
cmd-shift-v = '''exec-and-forget open -a 'Arc' 'https://www.bilibili.com/''''
cmd-shift-a = ['''exec-and-forget open -a 'Pearcleaner'''',
'''exec-and-forget open -a 'Latest''''
]


[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
alt-shift-semicolon = [
    'fullscreen',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

# Event listeners

## Chat

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
if.window-title-regex-substring = '^(?!WeChat \(Chats\)|微信 \(聊天\)).*$'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.tencent.xinWeChat'
run = 'move-node-to-workspace Chat'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.hnc.Discord'
run = 'move-node-to-workspace Chat'

[[on-window-detected]]
if.app-id = 'com.tinyspec.slackmacgap'
run = 'move-node-to-workspace Chat'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace Chat'

## Browsers

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace Brow'

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace Brow'

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
if.window-title-regex-substring = '(Picture-in-Picture|画中画|扩展)'
run = 'layout floating'
check-further-callbacks = true

[[on-window-detected]]
if.window-title-regex-substring = '(浏览器|browser|edge|chrome|vivaldi|zen|firefox|tor|librewolf|waterfox|brave|opera)'
run = 'move-node-to-workspace Brow'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = 'move-node-to-workspace Brow'

## Write

[[on-window-detected]]
if.app-id = 'com.electron.logseq'
run = 'move-node-to-workspace Wri'

[[on-window-detected]]
if.app-id = 'abnerworks.Typora'
run = 'move-node-to-workspace Wri'

[[on-window-detected]]
if.app-id = 'net.xmind.vana.app'
run = 'move-node-to-workspace Wri'

[[on-window-detected]]
if.app-id = 'com.apple.mobilenotes'
run = 'move-node-to-workspace Wri'

## Dev

[[on-window-detected]]
if.app-id = 'com.firstversionist.polypane'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'com.luckymarmot.Paw'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'com.haystack.software.editor'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'app.responsively'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'com.todesktop.230313mzl4w4u92'
run = 'move-node-to-workspace Dev'

[[on-window-detected]]
if.app-id = 'app.codeedit.CodeEdit'
run = 'move-node-to-workspace Dev'

## Read

[[on-window-detected]]
if.app-id = 'is.follow'
run = 'move-node-to-workspace Read'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.calibre'
run = 'move-node-to-workspace Read'

[[on-window-detected]]
if.app-id = 'com.apple.iBooksX'
run = 'move-node-to-workspace Read'

## Vorks

[[on-window-detected]]
if.app-id = 'asc.onlyoffice.ONLYOFFICE'
run = 'move-node-to-workspace Vork'

[[on-window-detected]]
if.app-id = 'com.mimestream.Mimestream'
run = 'move-node-to-workspace Vork'

## Floaters

[[on-window-detected]]
if.app-id = 'ch.protonvpn.mac'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.cisco.secureclient.gui'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.FaceTime'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.macpaw.CleanMyMac4'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ScreenContinuity'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.rogueamoeba.audiohijack'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.colliderli.iina'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Preview'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.QotoQot.Qbserve'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.runningwithcrayons.Alfred'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'sketchybar'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.zoboat.SnapBox'
run = 'layout floating'

[[on-window-detected]]
if.window-title-regex-substring = '(setting|设置|preference|偏好设置|配置)'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.ActivityMonitor'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.noodlesoft.Hazel'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.Dictionary'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'ru.keepcoder.Telegram'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.SFSymbols'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apple.iCal'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'cc.ffitch.shottr'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.alienator88.Pearcleaner'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.barebones.bbedit'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.onmyway133.Almighty'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.max-langer.Latest'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.davidbures.cork'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'cx.c3.theunarchiver'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.memoryvault.MemoryVault'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.itone.ProcessSpy'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.philipyoungg.session'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.sublimetext.4'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.apptorium.SideNotes-paddle'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'cn.better365.iRightMouseLite'
run = 'layout floating'

