#!/usr/bin/env bash

# 禁用自动大写
defaults write -g 'NSAutomaticCapitalizationEnabled' -bool NO
# 禁用自动破折号替换
defaults write -g 'NSAutomaticDashSubstitutionEnabled' -bool NO
# 禁用自动句号替换
defaults write -g 'NSAutomaticPeriodSubstitutionEnabled' -bool NO
# 禁用自动引号替换
defaults write -g 'NSAutomaticQuoteSubstitutionEnabled' -bool NO
# 禁用自动拼写纠正
defaults write -g 'NSAutomaticSpellingCorrectionEnabled' -bool NO

# 默认展开保存面板
defaults write -g 'NSNavPanelExpandedStateForSaveMode' -bool YES
# 默认展开保存面板（保存模式2）
defaults write -g 'NSNavPanelExpandedStateForSaveMode2' -bool YES

# 默认展开打印面板
defaults write -g 'PMPrintingExpandedStateForPrint' -bool YES
# 默认展开打印面板（打印2）
defaults write -g 'PMPrintingExpandedStateForPrint2' -bool YES

# 自动隐藏和显示Dock
defaults write com.apple.dock 'autohide' -bool YES
# 将窗口最小化到应用程序图标中
defaults write com.apple.dock 'minimize-to-application' -bool YES
# 不要根据最近使用的情况自动重新排列空间
defaults write com.apple.dock 'mru-spaces' -bool NO
# 不在Dock中显示最近的应用程序
defaults write com.apple.dock 'show-recents' -bool NO
# 设置左下角热角启动屏幕保护程序
defaults write com.apple.dock 'wvous-bl-corner' -int 14
# 设置右下角热角显示桌面
defaults write com.apple.dock 'wvous-br-corner' -int 4
# 设置左上角热角
defaults write com.apple.dock 'wvous-tl-corner' -int 2
# 设置右上角热角
defaults write com.apple.dock 'wvous-tr-corner' -int 12

# 显示所有文件扩展名
defaults write com.apple.finder 'AppleShowAllExtensions' -bool YES
# defaults write com.apple.finder 'CreateDesktop' -bool NO # https://github.com/koekeishiya/yabai/issues/863#issuecomment-1953184269
# 禁用标准点击显示桌面?
defaults write com.apple.WindowManager EnableStandardClickToShowDesktop -bool false
# 设置默认搜索范围?
defaults write com.apple.finder 'FXDefaultSearchScope' -string 'SCcf'
# 禁用扩展名更改警告
defaults write com.apple.finder 'FXEnableExtensionChangeWarning' -bool NO
# 设置首选视图样式
defaults write com.apple.finder 'FXPreferredViewStyle' -string 'clmv'
# 显示路径栏
defaults write com.apple.finder 'ShowPathbar' -bool YES
# 在标题中显示POSIX路径
defaults write com.apple.finder '_FXShowPosixPathInTitle' -bool YES

# 禁用屏幕截图阴影
defaults write com.apple.screencapture 'disable-shadow' -bool YES
# 设置屏幕截图保存位置
defaults write com.apple.screencapture 'location' -string "$HOME/Pictures/Screenshots"

# 启用自动检查更新
defaults write com.apple.SoftwareUpdate 'AutomaticCheckEnabled' -bool NO
# 启用自动下载更新 nah
defaults write com.apple.SoftwareUpdate 'AutomaticDownload' -int 1
# 启用关键更新自动安装
defaults write com.apple.SoftwareUpdate 'CriticalUpdateInstall' -int 1
# 设置更新检查频率
defaults write com.apple.SoftwareUpdate 'ScheduleFrequency' -int 1

# 禁止在网络存储上写入.DS_Store文件
defaults write com.apple.desktopservices 'DSDontWriteNetworkStores' -bool YES
# 禁止在USB存储上写入.DS_Store文件
defaults write com.apple.desktopservices 'DSDontWriteUSBStores' -bool YES

# 启用屏幕保护程序密码
defaults write com.apple.screensaver 'askForPassword' -int 1
# 设置屏幕保护程序密码延迟为0
defaults write com.apple.screensaver 'askForPasswordDelay' -int 0

# 强制使用24小时制
defaults write -g 'AppleICUForce24HourTime' -bool YES
# 设置界面风格为暗色
defaults write -g 'AppleInterfaceStyle' -string 'Dark'
# 启用键盘辅助模式
defaults write -g 'AppleKeyboardUIMode' -int 3
# 禁用按住键重复
defaults write -g 'ApplePressAndHoldEnabled' -bool NO
# 显示所有文件扩展名
defaults write -g 'AppleShowAllExtensions' -bool YES
# 显示所有文件
defaults write -g 'AppleShowAllFiles' -bool YES
# 设置滚动条显示方式为滚动时显示
defaults write -g 'AppleShowScrollBars' -string 'WhenScrolling'
# 设置窗口标签模式为全屏?
defaults write -g 'AppleWindowTabbingMode' -string 'fullscreen'
# 设置初始键重复延迟
defaults write -g 'InitialKeyRepeat' -int 20
# 设置键重复速度
defaults write -g 'KeyRepeat' -int 3
# 隐藏菜单栏
defaults write -g '_HIHideMenuBar' -bool YES
# 启用滚动方向自然
defaults write -g 'com.apple.swipescrolldirection' -bool YES
# 设置触控板缩放速度
defaults write -g 'com.apple.trackpad.scaling' -float 2.400000
# 设置系统提示音
defaults write .GlobalPreferences 'com.apple.sound.beep.sound' -string '/System/Library/Sounds/hero'
# 禁用个性化广告
defaults write com.apple.AdLib 'allowApplePersonalizedAdvertising' -bool NO
# 打印完成后自动退出
defaults write com.apple.print.PrintingPrefs 'Quit When Finished' -bool YES
# 启用窗口拖动手势
defaults write -g NSWindowShouldDragOnGesture YES
# 禁用窗口动画
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false